# E-Commerce Profitability Analysis

### 1. Import Data and Explore

In [1]:
import pandas as pd
import numpy as np

#### 1.1 Load all three CSV

In [2]:
orders = pd.read_csv(r'D:\Data Analysis\1.Projects\6.E-Commerce Profitability Analysis\resources\orders.csv')

In [ ]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          2000 non-null   object
 1   customer_id       2000 non-null   object
 2   order_date        2000 non-null   object
 3   channel           2000 non-null   object
 4   payment_method    2000 non-null   object
 5   region            2000 non-null   object
 6   items_ordered     2000 non-null   int64
 7   primary_category  2000 non-null   object
 8   gross_revenue     2000 non-null   float64
 9   discount_pct      2000 non-null   int64
 10  discount_amount   2000 non-null   float64
 11  shipping_cost     2000 non-null   float64
 12  product_cost      2000 non-null   float64
 13  platform_fee      2000 non-null   float64
 14  transaction_fee   2000 non-null   float64
 15  returned          2000 non-null   object
 16  refund_amount     2000 non-null   float64
 17  net_revenue       2000 non-null   float64
 18  total_costs       2000 non-null   float64
 19  profit            2000 non-null   float64
dtypes: float64(10), int64(2), object(8)
memory usage: 312.6+ KB

In [5]:
marketing_spend = pd.read_csv(r'D:\Data Analysis\1.Projects\6.E-Commerce Profitability Analysis\resources\marketing_spend.csv')

In [11]:
marketing_spend.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   month               144 non-null    object
 1   platform            144 non-null    object
 2   spend               144 non-null    float64
 3   impressions         144 non-null    int64
 4   clicks              144 non-null    int64
 5   conversions         144 non-null    int64
 6   revenue_attributed  144 non-null    float64
 7   cpc                 144 non-null    float64
 8   cpa                 144 non-null    float64
 9   roas                144 non-null    float64
dtypes: float64(5), int64(3), object(2)
memory usage: 11.4+ KB

In [3]:
products = pd.read_csv(r'D:\Data Analysis\1.Projects\6.E-Commerce Profitability Analysis\resources\products.csv')

In [5]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          2000 non-null   object
 1   customer_id       2000 non-null   object
 2   order_date        2000 non-null   object
 3   channel           2000 non-null   object
 4   payment_method    2000 non-null   object
 5   region            2000 non-null   object
 6   items_ordered     2000 non-null   int64
 7   primary_category  2000 non-null   object
 8   gross_revenue     2000 non-null   float64
 9   discount_pct      2000 non-null   int64
 10  discount_amount   2000 non-null   float64
 11  shipping_cost     2000 non-null   float64
 12  product_cost      2000 non-null   float64
 13  platform_fee      2000 non-null   float64
 14  transaction_fee   2000 non-null   float64
 15  returned          2000 non-null   object
 16  refund_amount     2000 non-null   float64
 17  net_revenue       2000 non-null   float64
 18  total_costs       2000 non-null   float64
 19  profit            2000 non-null   float64
 20  Unnamed: 20       2000 non-null   int64
dtypes: float64(10), int64(3), object(8)
memory usage: 328.3+ KB

#### 1.2 Verify the Correctness of Total Costs

In [9]:
orders['verify'] = round(orders['product_cost'] + orders['platform_fee'] + orders['transaction_fee'] + orders['shipping_cost'] - orders['total_costs'],2)
orders[orders['verify'] != 0][['order_id','verify']]

Empty DataFrame
Columns: [order_id, verify]
Index: []

In [ ]:
# All the total costs are caculated correctly

#### 1.3 Check for any data quality issues.

### 2.Category Profitability
#### Group orders by product category.
#### Calculate total revenue, total costs, total profit, and profit margin for each.
#### Identify the top and bottom performers.

In [18]:
orders_by_category = orders.groupby('primary_category')['order_id'].count().reset_index(name = 'number_of_orders')
orders_by_category.sort_values('number_of_orders',ascending = False,inplace=True)

In [19]:
orders_by_category

  primary_category  number_of_orders
2         Clothing               293
6           Sports               292
3      Electronics               267
7             Toys               257
4  Food & Beverage               247
1            Books               239
0           Beauty               205
5   Home & Kitchen               200

In [23]:
category_aggregation = orders.groupby('primary_category').agg(total_revenue = ('gross_revenue','sum'),
                                                                          total_costs = ('total_costs','sum')).reset_index()
category_aggregation['total_profit'] = category_aggregation['total_revenue'] - category_aggregation['total_costs']
category_aggregation['margin_profit'] = round(category_aggregation['total_profit'] / category_aggregation['total_revenue'] * 100,2)

In [27]:
category_aggregation.sort_values('margin_profit',ascending = False, inplace = True)
category_aggregation

  primary_category  total_revenue  total_costs  total_profit  margin_profit
3      Electronics       52876.49     30912.38      21964.11          41.54
4  Food & Beverage       36878.52     23070.92      13807.60          37.44
7             Toys       39081.00     24809.43      14271.57          36.52
5   Home & Kitchen       30879.43     19671.19      11208.24          36.30
6           Sports       37453.25     24733.20      12720.05          33.96
2         Clothing       37515.60     25110.65      12404.95          33.07
0           Beauty       20871.36     15079.19       5792.17          27.75
1            Books       22413.48     16597.58       5815.90          25.95

In [ ]:
# The highest profitable category is Electronics, and the lowest is Books